export const eventAppConfig = {
  eventName: "TEDxNTUA",
  eventDate: "Saturday, 9 May 2026",
  adminPass: "tedxadmin2026",
  firebase: {
    apiKey: "AIzaSyC8In2nvqKBVU4VCdI6H8Zp34r5pCbtWE4",
    projectId: "tedxntua-2026-1a82a",
  },
  schedule: [
    { time: "10:00", title: "Registration", type: "break" },
    { time: "11:15", title: "Unforgetable", speaker: "Unforgetable", initials: "UF", performerId: "pf1", tag: "Performance" },
    { time: "11:30", title: "Opening", type: "break" },
    { time: "11:50", title: "Ελένη Καββάδα", speaker: "Ελένη Καββάδα", initials: "ΕΚ", speakerId: "s1", tag: "Talk" },
    { time: "12:10", title: "Στέργιος Βακάλης", speaker: "Στέργιος Βακάλης", initials: "ΣΒ", speakerId: "s2", tag: "Talk" },
    { time: "12:30", title: "1st Break - Workshops: The American College of Greece, AlphaBank, Souxoumouxou", type: "break" },
    { time: "13:45", title: "Μάριος Ψαριανός", speaker: "Μάριος Ψαριανός", initials: "ΜΨ", performerId: "pf2", tag: "Performance" },
    { time: "14:00", title: "Θάνος Ιωαννίδης & Χαρά Κοντοχρήστου", speaker: "Θάνος Ιωαννίδης & Χαρά Κοντοχρήστου", initials: "ΘΙ", speakerId: "s3", tag: "Talk" },
    { time: "14:20", title: "Νάσος Κατσαμάνης", speaker: "Νάσος Κατσαμάνης", initials: "ΝΚ", speakerId: "s4", tag: "Talk" },
    { time: "14:40", title: "Δημήτρης Μπάρμπας", speaker: "Δημήτρης Μπάρμπας", initials: "ΔΜ", speakerId: "s5", tag: "Talk" },
    { time: "15:00", title: "2nd Break - Workshops: Dialectica, Oliver Wyman, Wabi Sabi Lab", type: "break" },
    { time: "16:15", title: "Black Brides", speaker: "Black Brides", initials: "BB", performerId: "pf1", tag: "Performance" },
    { time: "16:30", title: "Έλενα Παπαδημητρίου", speaker: "Έλενα Παπαδημητρίου", initials: "ΕΠ", speakerId: "s6", tag: "Talk" },
    { time: "16:50", title: "Δημήτρης Σαμόλης", speaker: "Δημήτρης Σαμόλης", initials: "ΔΣ", speakerId: "s7", tag: "Talk" },
    { time: "17:10", title: "Στράτος Φυγετάκης", speaker: "Στράτος Φυγετάκης", initials: "ΣΦ", performerId: "pf3", tag: "Performance" },
    { time: "17:25", title: "3rd Break - Workshops: Athenaides", type: "break" },
    { time: "18:40", title: "Γιάννης Δαγκλής", speaker: "Γιάννης Δαγκλής", initials: "ΓΔ", speakerId: "s8", tag: "Talk" },
    { time: "19:00", title: "Νόρα Δράκου", speaker: "Νόρα Δράκου", initials: "ΝΔ", speakerId: "s9", tag: "Talk" },
    { time: "19:20", title: "KONIKOU", speaker: "KONIKOU", initials: "KN", performerId: "pf4", tag: "Performance" },
    { time: "19:35", title: "Closing", type: "break" },
    { time: "20:00", title: "After Party", type: "break" },
  ],
  speakers: [
    { id: "s1", name: "Ελένη Καββάδα", role: "Ιδρύτρια του brand υψηλής ραπτικής και installation 240791", photo: "photo_kavvada.png", tag: "Talk", bio: "Η ομιλία πραγματεύεται τη σημαντικότητα του κώδικα 0 σαν ταυτότητα του καλλιτέχνη και την ισχύ της προσωπικής υπογραφής σε έναν κόσμο με πληθώρα πληροφορίας και επιλογών." },
    { id: "s2", name: "Στέργιος Βακάλης", role: "Επίκουρος Καθηγητής Ενεργειακών Διεργασιών", photo: "photo_vakalis.png", tag: "Talk", bio: "Η ομιλία εισάγει το Cycle 0 ως τρόπο κατανόησης της προόδου: όχι ως γραμμική πορεία προς την τελειότητα, αλλά ως επαναληπτική διαδικασία δοκιμής, προσαρμογής και εξέλιξης." },
    { id: "s3", name: "Θάνος Ιωαννίδης & Χαρά Κοντοχρήστου", role: "Αρχιτέκτονας Μηχανικός / Content Creator", photo: "photo_thanos&chara.png", tag: "Talk", bio: "Η ομιλία πραγματεύεται την αρχιτεκτονική ως διαδικασία και αφήγηση, μέσα από το έργο του Erion Workshop και το format «Αρχιτεκτονική για το παγωτό σας»." },
    { id: "s4", name: "Νάσος Κατσαμάνης", role: "Co-founder at Auxilis AI & Διευθυντής Ερευνών στο Ερευνητικό Κέντρο «Αθηνά»", photo: "photo-katsamanis.png", tag: "Talk", bio: "Στο μικροσκόπιο μπαίνει η νέα πραγματικότητα της υγείας, εκεί όπου οι AI agents αποδεσμεύουν τον γιατρό από τη γραφειοκρατία και επιστρέφουν χρόνο στη φροντίδα." },
    { id: "s5", name: "Δημήτρης Μπάρμπας", role: "Music Content Creator, Vocal Coach & Podcaster", photo: "photo_dimitris_barbas.png", tag: "Talk", bio: "Το θέμα είναι η επανάληψη στη μουσική μέσα από ομόκεντρους κύκλους επαναληψιμότητας: στο τραγούδι, στη δισκογραφία, στα είδη και στη μουσική ιστορία." },
    { id: "s6", name: "Έλενα Παπαδημητρίου", role: "Δημοσιογράφος", photo: "photo_papadimitriou.png", tag: "Talk", bio: "Τι είναι και τι δεν είναι είδηση; Πού αρχίζει και πού τελειώνει η δημοσιογραφική δουλειά στην εποχή των social media;" },
    { id: "s7", name: "Δημήτρης Σαμόλης", role: "Ηθοποιός-Τραγουδοποιός", photo: "photo_samolhs.png", tag: "Talk", bio: "Ο Δημήτρης Σαμόλης μιλά για τον κύκλο των αντιθέσεων που διατρέχει την ύπαρξή μας, από το τραύμα μέχρι τη θεραπεία και από τη σιωπή μέχρι την έκφραση." },
    { id: "s8", name: "Γιάννης Δαγκλής", role: "Καθηγητής Διαστημικής Φυσικής", photo: "photo_daglis.png", tag: "Talk", bio: "Η ομιλία μιλά για την κυκλικότητα της μαγνητικής δραστηριότητας του Ήλιου και πώς αυτή αντανακλάται σε φαινόμενα του γεωδιαστήματος." },
    { id: "s9", name: "Νόρα Δράκου", role: "Κολυμβήτρια της Εθνικής Ομάδας Ελλάδας, 4 φορές Ολυμπιονίκης", photo: "photo_drakou.png", tag: "Talk", bio: "Η Νόρα Δράκου μιλά για τη διαδρομή πίσω από την κορυφή, τη δύναμη της επανάληψης, την πειθαρχία και το τίμημα της συνέπειας στον χρόνο." },
  ],
  performers: [
    { id: "pf1", name: "GET AP", role: "Χορευτική Ομάδα", photo: "photo_getup.png", tag: "Performance", desc: "" },
    { id: "pf2", name: "Μάριος Ψαριανός", role: "Τραγουδιστής", photo: "photo_psarianos.png", tag: "Performance", desc: "Ο Μάριος Ψαριανός είναι τραγουδοποιός και ερμηνευτής της σύγχρονης ελληνικής σκηνής, με βιωματική σχέση με το τραγούδι και προσωπικό ήχο." },
    { id: "pf3", name: "Στράτος Φυγετάκης", role: "Indie καλλιτέχνης", photo: "photo_fygetakis.png", tag: "Performance", desc: "Ο Stratos Fygetakis χτίζει έναν προσωπικό ήχο ανάμεσα στην indie, την pop και τη folk, με τραγούδια που εξερευνούν τη νεότητα και τη μετάβαση." },
    { id: "pf4", name: "KONIKOU", role: "Τραγουδίστρια", photo: "photo_konikou.png", tag: "Performance", desc: "Η KONIKOU έρχεται στη σκηνή του TEDxNTUA 2026 για να συνδυάσει τη μουσική με τους κύκλους που επαναλαμβάνονται στις ανθρώπινες σχέσεις." },
  ],
  workshops: [
    { id: "wp1", name: "The American College of Greece", type: "pro", typeLabel: "Professional", seats: 40, time: "12:30 - 13:45", desc: "Περιγραφή workshop σύντομα διαθέσιμη." },
    { id: "wp2", name: "AlphaBank", type: "pro", typeLabel: "Professional", seats: 40, time: "12:30 - 13:45", desc: "Περιγραφή workshop σύντομα διαθέσιμη." },
    { id: "wp3", name: "Dialectica", type: "pro", typeLabel: "Professional", seats: 40, time: "15:00 - 16:15", desc: "Περιγραφή workshop σύντομα διαθέσιμη." },
    { id: "wp4", name: "Oliver Wyman", type: "pro", typeLabel: "Professional", seats: 40, time: "15:00 - 16:15", desc: "Περιγραφή workshop σύντομα διαθέσιμη." },
    { id: "we1", name: "Souxoumouxou", type: "exp", typeLabel: "Experience", seats: 15, time: "12:30 - 13:45", desc: "Περιγραφή experience σύντομα διαθέσιμη." },
    { id: "we2", name: "Wabi Sabi Lab", type: "exp", typeLabel: "Experience", seats: 30, time: "15:00 - 16:15", desc: "Περιγραφή experience σύντομα διαθέσιμη." },
    { id: "we5", name: "Athenaides", type: "exp", typeLabel: "Experience", seats: 15, time: "17:25 - 18:40", desc: "Περιγραφή workshop σύντομα διαθέσιμη." },
  ],
  giveaways: [
    { id: "gw1", name: "Giveaway #1", prize: "Gift details coming soon", formUrl: "https://forms.gle/LINK_1" },
    { id: "gw2", name: "Giveaway #2", prize: "Gift details coming soon", formUrl: "https://forms.gle/LINK_2" },
    { id: "gw3", name: "Giveaway #3", prize: "Gift details coming soon", formUrl: "https://forms.gle/LINK_3" },
  ],
};
